[package]
name = "translator"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.32.3"
rfd = "0.15.4"
regex = "1.7"
winapi = { version = "0.3.9", features = ["winuser", "windef"] }
lazy_static = "1.4"

[dev-dependencies]
mockall = "0.13"